[system]
description = "Creating multiple of a single component (ping) with distinct id's via chkpnt booter"

[[components]]
name = "booter"
img  = "no_interface.llbooter"
implements = [{interface = "init"}]
deps = [{srv = "kernel", interface = "init", variant = "kernel"}]
constructor = "kernel"

[[components]]
name = "pong"
img  = "pong.pingpong"
deps = [{srv = "booter", interface = "init"}]
baseaddr = "0x1600000"
constructor = "booter"