[system]
description = "Simple system: the ping pong test for IPC and shared VAS"

[[components]]
name = "booter"
img  = "no_interface.llbooter"
implements = [{interface = "init"}]
deps = [{srv = "kernel", interface = "init", variant = "kernel"}]
constructor = "kernel"

[[components]]
name = "ping"
img  = "tests.unit_pingshvas"
deps = [{srv = "pong", interface = "pong"},
        {srv = "booter", interface = "init"}]
baseaddr = "0x40000000"
constructor = "booter"

[[components]]
name = "pong"
img  = "pong.pingpong"
deps = [{srv = "booter", interface = "init"}]
implements = [{interface = "pong"}]
baseaddr = "0x10000000000"
constructor = "booter"
