[system]
description = "Simple system: the ping pong test for IPC, and initialization ordering"

[[components]]
name = "booter"
img  = "no_interface.llbooter"
implements = [{interface = "init"}]
deps = [{srv = "kernel", interface = "init", variant = "kernel"}]
constructor = "kernel"

[[components]]
name = "ping"
img  = "tests.unit_pingpong"
deps = [{srv = "pong1", interface = "pong"},
        {srv = "booter", interface = "init"}]
baseaddr = "0x1600000"
constructor = "booter"

[[components]]
name = "pong1"
img  = "pong.pingpong"
deps = [{srv = "booter", interface = "init"}, 
        {srv = "pong2", interface = "pong"}]
implements = [{interface = "pong"}]
baseaddr = "0x18CBA80"
constructor = "booter"

[[components]]
name = "pong2"
img  = "pong.pingpong2"
deps = [{srv = "booter", interface = "init"}]
implements = [{interface = "pong"}]
baseaddr = "0x2000000"
constructor = "booter"