[system]
description = "Simple system: Pong server in different NS than Ping client"

[[components]]
name = "booter"
img  = "no_interface.llbooter"
implements = [{interface = "init"}]
deps = [{srv = "kernel", interface = "init", variant = "kernel"}]
constructor = "kernel"

[[components]]
name = "ping"
img  = "tests.unit_pingpong"
deps = [{srv = "pong", interface = "pong"},
        {srv = "booter", interface = "init"}]
baseaddr = "0x1600000"
constructor = "booter"

[[components]]
name = "pong"
img  = "pong.pingpong"
deps = [{srv = "booter", interface = "init"}]
implements = [{interface = "pong"}]
baseaddr = "0x18CBA80"
constructor = "booter"