[system]
description = "Simple system with 3 components and a booter. Two of the components are in the same VAS and one is isolated from them."

[[components]]
name = "booter"
img  = "no_interface.llbooter_shvas"
implements = [{interface = "init"}]
deps = [{srv = "kernel", interface = "init", variant = "kernel"}]
constructor = "kernel"

[[components]]
name = "pingshvas"
img  = "tests.unit_pingshvas"
deps = [{srv = "pongshvas", interface = "pongshvas"},
        {srv = "booter", interface = "init"}]
baseaddr = "0x40000000"
constructor = "booter"

[[components]]
name = "pongshvas"
img  = "tests.unit_pongshvas"
deps = [{srv = "booter", interface = "init"},
        {srv = "pang", interface = "pang"}]
implements = [{interface = "pongshvas"}]
baseaddr = "0x10000000000"
constructor = "booter"

[[components]]
name = "pang"
img  = "tests.unit_pang"
deps = [{srv = "booter", interface = "init"}]
implements = [{interface = "pang"}]
constructor = "booter"
