[system]
description = "Test to see if 2 components can be allocated into the same namespace"

[[components]]
name = "booter"
img  = "no_interface.llbooter"
implements = [{interface = "init"}]
deps = [{srv = "kernel", interface = "init", variant = "kernel"}]
constructor = "kernel"

[[components]]
name = "ns_vas_1"
img  = "tests.vas_namespaces"
deps = [{srv = "booter", interface = "init"}]
baseaddr = "0x1600000"
constructor = "booter"

[[components]]
name = "ns_vas_2"
img  = "tests.vas_namespaces"
deps = [{srv = "booter", interface = "init"}]
baseaddr = "0x18CBA80"
constructor = "booter"