[system]
description = "Simple test to see if the VAS namespace allocation is working"

[[components]]
name = "booter"
img  = "no_interface.llbooter"
implements = [{interface = "init"}]
deps = [{srv = "kernel", interface = "init", variant = "kernel"}]
constructor = "kernel"

[[components]]
name = "ns_vas_test"
img  = "tests.vas_namespaces"
deps = [{srv = "booter", interface = "init"}]
baseaddr = "0x1600000"
constructor = "booter"